# Generated by Django 2.2.10 on 2020-04-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('song_title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
