# Generated by Django 2.2.10 on 2020-04-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='album_logo',
            new_name='image',
        ),
    ]
